---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postal
spec:
  template:
    spec:
      containers:
        - name: postal
          image: shokohsc/postal
          env:
            - name: ENV
              value: development
            - name: API_GATEWAY_HOST
              value: dev.sidekick.shokohsc.home
            - name: API_GATEWAY_PORT
              value: "443"
            - name: USE_SENTRY
              value: "true"
            - name: SENTRY_DSN
              value: https://2f15ffed2e254ced911e78de9312afe0\@glitchtip.shokohsc.home/1
            - name: SENTRY_AUTH_TOKEN
              value: db6ff5f7b002322a0b6800027fa823d5faa131dc2535e060375d902728ea8353
            - name: SENTRY_PROJECT
              value: dev
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 512M
